vim.opt.guifont = { "Fira Code iScript", "h18" }
vim.api.nvim_set_hl(0, 'Comment', { italic=true })
require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"
spec "user.colorscheme"
spec "user.devicons"
spec "user.treesitter"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.cmp"
spec "user.none-ls"
spec "user.whichkey"
spec "user.telescope"
spec "user.nvimtree"
spec "user.comment"
spec "user.lualine"
spec "user.navic"
spec "user.breadcrumbs"
spec "user.illuminate"
spec "user.autopairs"
spec "user.extras.tabby"
spec "user.extras.oil"
spec "user.extras.colorizer"
spec "user.extras.eyeliner"
require "user.lazy"
