eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(zoxide init zsh)"
eval $(thefuck --alias)
eval $(thefuck --alias fk)
eval "$(starship init zsh)"
export PATH=$PATH:/usr/local/bin
export ZSH="$HOME/.oh-my-zsh"
export ZSH_TMUX_AUTOSTART=false
export ZSH_TMUX_AUTOCONNECT=true
# ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  zsh-autosuggestions
  zsh-syntax-highlighting
  tmux
)
source $ZSH/oh-my-zsh.sh
source ~/.p10k.zsh

source ${HOME}/.config/zsh/loading_config
source ${HOME}/.config/zsh/loading_alias

# Added by dbt installer
export PATH="$PATH:/Users/joma/.local/bin"
export STARSHIP_CONFIG=~/.config/starship/starship.toml


# if [[ -o interactive ]]; then
# fastfetch
# fi
#
# Auto-deactivate virtual environment when changing directories
chpwd() {
    if [[ -n "$VIRTUAL_ENV" ]]; then
        # Check if we're still in a subdirectory of the virtual environment
        if [[ "$PWD"/ != "$VIRTUAL_ENV"/* ]] && [[ "$PWD" != "$VIRTUAL_ENV" ]]; then
            deactivate
        fi
    fi
}


# dbt aliases
alias dbtf=/Users/joma/.local/bin/dbt
