# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
eval "$(/opt/homebrew/bin/brew shellenv)"

# ---- Zoxide (better cd) ----
eval "$(zoxide init zsh)"

# ---- Thefuck ----
# Thefuck is a tool that corrects your previous console command.
# It can be installed via pip: pip install thefuck
eval $(thefuck --alias)
eval $(thefuck --alias fk)

export PATH=$PATH:/usr/local/bin
export ZSH="$HOME/.oh-my-zsh"

# ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)
source $ZSH/oh-my-zsh.sh
source ~/.p10k.zsh

source ${HOME}/.config/zsh/loading_config
source ${HOME}/.config/zsh/loading_alias
export EDITOR=nvim
# if command -v tmux &> /dev/null && [ -z "$TMUX" ]; then
#   tmux attach-session  || tmux new-session
# fi


# Added by dbt installer
export PATH="$PATH:/Users/joma/.local/bin"

# dbt aliases
alias dbtf=/Users/joma/.local/bin/dbt

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


eval "$(starship init zsh)"
export STARSHIP_CONFIG=~/.config/starship/starship.toml


# if [[ -o interactive ]]; then
# fastfetch
# fi
